/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasinoPoke;

import javax.swing.JOptionPane;

/**
 *
 * @author Corella
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        bttNext.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxTName = new javax.swing.JTextField();
        TxTlasname = new javax.swing.JTextField();
        TxTID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bttNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter your name: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 36));

        jLabel3.setText("Enter your ID: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        jLabel4.setText("Enter your last name: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));
        jPanel1.add(TxTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 158, -1));
        jPanel1.add(TxTlasname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 157, -1));
        jPanel1.add(TxTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 157, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 180, -1, -1));

        bttNext.setText("Next");
        bttNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNextActionPerformed(evt);
            }
        });
        jPanel1.add(bttNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMoradoLose (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNextActionPerformed

        FrCasinoPokemon frame = new FrCasinoPokemon();
        dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_bttNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idk = JOptionPane.YES_NO_OPTION;
        Cola cola = new Cola();

        String namel = TxTName.getText();
        String lastnamel = TxTlasname.getText();
        int idl = Integer.parseInt(TxTID.getText());

        boolean encontrado = false;

        for (Listas lista : cola.colaData) {
            if (lista.getNombre().equals(namel) && lista.getApellido().equals(lastnamel) && lista.getID() == idl) {
                int desi = JOptionPane.showConfirmDialog(null, "Are you " + namel + "? \nDo you want to login as " + namel + "?", "Ask", idk);

                if (desi == 1) {
                    JOptionPane.showMessageDialog(null, "Perfect! enter again");
                    TxTName.setText("");
                    TxTlasname.setText("");
                    TxTID.setText("");
                    return;
                } else {
                    JOptionPane.showMessageDialog(null, "Perfect, it's a pleasure to have you back " + namel);
                    bttNext.setVisible(true);
                }
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            cola.addList(namel, lastnamel, idl);
            JOptionPane.showMessageDialog(null, "Registration has been completed");
            bttNext.setVisible(true);
        }
    

    }//GEN-LAST:event_jButton1ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxTID;
    private javax.swing.JTextField TxTName;
    private javax.swing.JTextField TxTlasname;
    private javax.swing.JButton bttNext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
