/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CasinoPoke;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Corella
 */
public class FrCasinoPokemon extends javax.swing.JFrame {

    private clase_pokemos_H_ pokebox_1;
    private clase_pokemos_H_ pokeBox_2;
    private clase_pokemos_H_ pokeBox_3;
    private String res1, res2, res3, res4;
    private int points = 1000;//$
    private int winnings ;//$
    private int losses =0;//$
    

    /**
     * Creates new form FrCasinoPokemon
     */
    public FrCasinoPokemon() {

        initComponents();
        setEnableBottons(false);
        Total.setText("1000$");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPokeBox2 = new javax.swing.JLabel();
        lblPokeBox3 = new javax.swing.JLabel();
        lblPokeBox1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bttStop1 = new javax.swing.JButton();
        bttStop2 = new javax.swing.JButton();
        bttStop3 = new javax.swing.JButton();
        bttStart = new javax.swing.JButton();
        bttStopALL = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        gastos = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblPokeBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 120, 150));
        jPanel1.add(lblPokeBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 110, 120));

        lblPokeBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(lblPokeBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 140, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marcoGame__1_-removebg-preview (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 710, 320));

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        bttStop1.setText("Stop 1");
        bttStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStop1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttStop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 110, 60));

        bttStop2.setText("Stop 2");
        bttStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStop2ActionPerformed(evt);
            }
        });
        jPanel1.add(bttStop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 110, 60));

        bttStop3.setText("Stop 3");
        bttStop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStop3ActionPerformed(evt);
            }
        });
        jPanel1.add(bttStop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 110, 60));

        bttStart.setText("Start");
        bttStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStartActionPerformed(evt);
            }
        });
        jPanel1.add(bttStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 110, 60));

        bttStopALL.setText("Stop all");
        bttStopALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStopALLActionPerformed(evt);
            }
        });
        jPanel1.add(bttStopALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 110, 60));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Remaining funds: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(153, 0, 153), new java.awt.Color(51, 153, 255)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 50));

        gastos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        gastos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(153, 0, 153)));
        jPanel1.add(gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, 50));

        Total.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(153, 0, 153)));
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gengarFondo (3).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setEnableBottons(boolean enable) {

        bttStop1.setEnabled(enable);;
        bttStop2.setEnabled(enable);
        bttStop3.setEnabled(enable);
        bttStopALL.setEnabled(enable);
    }

    private void points() {

    }
    private void bttStopALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStopALLActionPerformed

        pokebox_1.stop();
        pokeBox_2.stop();
        pokeBox_3.stop();
        setEnableBottons(false);
        res1 = pokebox_1.getpokiSelect();
        res2 = pokeBox_2.getpokiSelect();
        res3 = pokeBox_3.getpokiSelect();
        verificarBotones();
        Ganador();

    }//GEN-LAST:event_bttStopALLActionPerformed

    private void bttStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStartActionPerformed

        
        pokebox_1 = new clase_pokemos_H_("1erBox", lblPokeBox1);
        pokeBox_2 = new clase_pokemos_H_("2ndBox", lblPokeBox2);
        pokeBox_3 = new clase_pokemos_H_("3rdBox", lblPokeBox3);

        pokebox_1.start();
        pokeBox_2.start();
        pokeBox_3.start();

        setEnableBottons(true);
        res1 = "";
        res2 = "";
        res3 = "";
        points = points - 100;  
        losses=losses -100;
        game.setrecLosses(losses);
        
        verificarBotones();
        Total.setText(""+points+"$");
        gastos.setText("-100$");
        
        if (points < 100) {
            GameOverFrame game = new GameOverFrame();
            game.setrecLosses(losses);
            dispose();
            
            game.setVisible(true);
        }
        
    }//GEN-LAST:event_bttStartActionPerformed

    private void bttStop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStop3ActionPerformed
        pokeBox_3.stop();
        bttStop3.setEnabled(false);;
        res3 = pokeBox_3.getpokiSelect();
        System.out.println(res3);
        verificarBotones();
        Ganador();
    }//GEN-LAST:event_bttStop3ActionPerformed

    private void bttStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStop2ActionPerformed

        pokeBox_2.stop();
        bttStop2.setEnabled(false);;
        res2 = pokeBox_2.getpokiSelect();
        System.out.println(res2);
        verificarBotones();
        Ganador();
    }//GEN-LAST:event_bttStop2ActionPerformed

    private void bttStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStop1ActionPerformed
        // TODO add your handling code here:
        pokebox_1.stop();
        bttStop1.setEnabled(false);;
        res1 = pokebox_1.getpokiSelect();//Sacar ganador
        System.out.println(res1);
        verificarBotones();
        Ganador();

    }//GEN-LAST:event_bttStop1ActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        GameOverFrame game = new GameOverFrame();
        dispose();
        game.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Ganador() {//ARREGLAR ESTO

        if (res1 == res2 && res2 == res3) {

            JOptionPane.showMessageDialog(null, "¡Felicidades! Has ganado...."
                    + "\nNada... :(", "Ganador", JOptionPane.INFORMATION_MESSAGE);
            winnings= winnings+800;
            points = points + 800;
            
            game.setrecWinnings(winnings);
            
            Total.setText(""+points);
        }

        if (points < 100) {
            GameOverFrame game = new GameOverFrame();
            dispose();
            game.setVisible(true);
            
            points=1000;
            
        }

    }

    private void verificarBotones() {

        if (!bttStop1.isEnabled() && !bttStop2.isEnabled() && !bttStop3.isEnabled()) {
            bttStart.setEnabled(true);
        } else {
            bttStart.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */

    GameOverFrame game = new GameOverFrame();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton bttStart;
    private javax.swing.JButton bttStop1;
    private javax.swing.JButton bttStop2;
    private javax.swing.JButton bttStop3;
    private javax.swing.JButton bttStopALL;
    private javax.swing.JLabel gastos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPokeBox1;
    private javax.swing.JLabel lblPokeBox2;
    private javax.swing.JLabel lblPokeBox3;
    // End of variables declaration//GEN-END:variables
}
